name: Create and Publish Branches

on:
  pull_request: 
    types:
    - opened
    - closed

jobs:
  create-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2