name: Create and Publish Branches

on:
  push:
    branches:
      - dev

jobs:
  create-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Hello
        run: echo "Hello !" 
